### ISSUE TITLE
Can't show list client on tab service.

### ISSUE THREAD

**Issue by congto** [renatoalmeidaoliveira/nbservice#11]
Hi @renatoalmeidaoliveira !

I have tried to install nbservice with netbox 3.4.5 on docker environment.

The installation did not give any error but when I declared the service for the nbservice plugin, I had the problem that the client item was not displayed.

![image](https://user-images.githubusercontent.com/5918118/223959969-bd3c54f6-3ae9-4160-994a-a0ee51b086d8.png)

Can you explain this to me or show me how to check.
Thank you

**Comment by renatoalmeidaoliveira** [comment]
Hi @congto, the Clients field is a Multi Select Field filled by Tenants, so you need to create some Tenant before creating a service.

**Comment by congto** [comment]
Hi @renatoalmeidaoliveira 

![image](https://user-images.githubusercontent.com/5918118/224362061-4fd6e146-4ad6-4653-be1d-add20b4b2674.png)

I followed the instructions and it worked. Thank you, hope you continue to develop it, I will follow and learn how to use it.
