### ISSUE TITLE
Plugin broken on Netbox 3.7

### ISSUE THREAD

**Issue by captainCrench** [renatoalmeidaoliveira/nbservice#12]
It looks like some issues with forms as things may have been moved around.  Was able to verify this fixes it:

_from utilities.forms import BootstrapMixin
from utilities.forms.widgets import DatePicker
from utilities.forms.fields import DynamicModelMultipleChoiceField, DynamicModelChoiceField_

But when trying to add a service, I get a serializer exception so there may be more edits needed to get this to work on newer Netbox versions.

**Comment by captainCrench** [comment]
The error:
_Traceback (most recent call last):
  File "/opt/netbox/netbox/utilities/api.py", line 32, in get_serializer_for_model
    return dynamic_import(serializer_name)
  File "/opt/netbox/netbox/utilities/utils.py", line 126, in dynamic_import
    mod = getattr(mod, comp)
AttributeError: module 'nb_service.api.serializers' has no attribute 'ServiceSerializer'_

**Comment by misch42** [comment]
Error in my 3.7.3 setup:

Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "/opt/netbox-3.7.3/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
(...)
  File "/opt/netbox-3.7.3/venv/lib64/python3.9/site-packages/nb_service/forms.py", line 8, in <module>
    from utilities.forms import BootstrapMixin, DatePicker, DynamicModelMultipleChoiceField, DynamicModelChoiceField
ImportError: cannot import name 'DatePicker' from 'utilities.forms' (/opt/netbox-3.7.3/netbox/utilities/forms/__init__.py)

**Comment by opensourceXnetbox** [comment]
Same problem!

**Comment by renatoalmeidaoliveira** [comment]
@opensourceXnetbox, @misch42, @captainCrench please update the plugin to 2.0.0

**Comment by opensourceXnetbox** [comment]
> @opensourceXnetbox, @misch42, @captainCrench please update the plugin to 2.0.0

Hey @renatoalmeidaoliveira, thanks for the fix, it works perfectly.

**Comment by misch42** [comment]
thanks. works for me now.
