### ISSUE TITLE
Scrollbar

### ISSUE THREAD

**Issue by advaircarvalho** [renatoalmeidaoliveira/nbservice#4]
I noticed that when you have many related objects, the diagram is bad to visualize, because the bottom scroll bar does not appear in the browser. Could it be something programmable?

**Comment by advaircarvalho** [comment]
@renatoalmeidaoliveira horizontal scroll.

it would be interesting to also download the diagram in some format such as pdf, png or jpeg😀

**Comment by renatoalmeidaoliveira** [comment]
Hello @advaircarvalho, just added the horizontal scroll bar, and some SVG export features, it might have an Export Icon in the Diagram View.
To update your plugin please run:
```
source /opt/netbox/venv/bin/activate
pip install --upgrade nb-service
python3 /opt/netbox/netbox/manage.py collectstatic
service netbox restart
```
And if the problem persists please let me know.

**Comment by advaircarvalho** [comment]
It was very good, thank you.

Everything's solved.
