### ISSUE TITLE
Resource - Diagram with expand and collapse function

### ISSUE THREAD

**Issue by advaircarvalho** [renatoalmeidaoliveira/nbservice#5]
@renatoalmeidaoliveira A + and - (expand and collapse) feature in the diagram with objects that have multiple relationships would be interesting. This would make viewing large diagrams easier.

By the way, I also live in Brasília DF.

**Comment by renatoalmeidaoliveira** [comment]
Hello @advaircarvalho, nb-service diagrams are made with mermaid-js, and as in this [issue](https://github.com/mermaid-js/mermaid/issues/1123), that feature might not be implemented, so I think for now that can't be implemeted here.

About you living in Brasília DF, that's very cool :D, tomorow I'm going to IX Fórum Regional.
