### ISSUE TITLE
Plugin doesn't work in Netbox 3.4

### ISSUE THREAD

**Issue by Tais-A** [renatoalmeidaoliveira/nbservice#9]
When I try to click on the plugin link (Services and Applications) I have the below error returned:
![nb_service_error](https://user-images.githubusercontent.com/58663757/220165965-c1627fab-4452-4af9-9bb1-5bfadaac4a14.png)

**Comment by deku-m** [comment]
Having the same issue:

```
<class 'django.template.exceptions.TemplateSyntaxError'>

'applied_filters' did not receive value(s) for the argument(s): 'query_params'

Python version: 3.10.6
NetBox version: 3.4.5
```
